// ==UserScript==
// @name         Donorbox offline donation prefill
// @namespace    lrdc-offline-importer
// @version      1.0.1
// @description  Fills the Donorbox org-admin offline donation form from a URL hash payload (#dbOffline= or #!dbOffline=…) generated by the launcher (Vercel-hosted or local). You must be logged in; complete captcha and submit manually if required.
// @match        https://donorbox.org/org_admin/supporters/*/donor_donations/new*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

/**
 * Form field map (from Donorbox org-admin offline donation form HTML):
 * - Payment type:     select#donation_donation_type  (donation[donation_type])
 * - Donation date:    input#donation_donation_date
 * - Deposit date:     input#donation_offline_donation_additional_detail_attributes_deposit_date
 * - Amount:           input#amount
 * - Org note:         textarea#donation_org_comments
 * - Check # (opt):    input#donation_offline_donation_additional_detail_attributes_check_number
 */

(function () {
  'use strict';

  var HASH_PREFIX = 'dbOffline=';

  /**
   * Donorbox’s front-end uses a hashbang fragment (#!…). Links use #dbOffline=… but the
   * live URL often becomes #!dbOffline=…, so we must accept both (and any leading !).
   */
  function decodePayload(hash) {
    if (!hash || hash.charAt(0) !== '#') return null;
    var raw = hash.slice(1).replace(/^!+/, '');
    var idx = raw.indexOf(HASH_PREFIX);
    if (idx === -1) return null;
    var enc = raw.slice(idx + HASH_PREFIX.length);
    if (!enc) return null;
    var stop = enc.search(/[&\s]/);
    if (stop !== -1) enc = enc.slice(0, stop);
    try {
      var b64 = enc.replace(/-/g, '+').replace(/_/g, '/');
      while (b64.length % 4) b64 += '=';
      var json = decodeURIComponent(escape(atob(b64)));
      return JSON.parse(json);
    } catch (e) {
      console.warn('[Donorbox prefill] Invalid payload', e);
      return null;
    }
  }

  /** Map launcher keys plus a few alternates (manual tests, older links). */
  function normalizePayload(data) {
    if (!data || typeof data !== 'object') return null;
    return {
      donationType:
        data.donationType ||
        data.payment ||
        data.paymentType ||
        data.type ||
        data.donation_type ||
        '',
      donationDate:
        data.donationDate || data.date || data.donation_date || data.giftDate || '',
      depositDate: data.depositDate || data.deposit_date || data.bankDate || '',
      amount: data.amount != null && data.amount !== '' ? String(data.amount) : '',
      orgComments:
        data.orgComments ||
        data.notes ||
        data.note ||
        data.comment ||
        data.org_comment ||
        '',
      checkNumber: String(
        data.checkNumber != null && data.checkNumber !== ''
          ? data.checkNumber
          : data.check_number != null && data.check_number !== ''
            ? data.check_number
            : data.check != null && data.check !== ''
              ? data.check
              : ''
      ),
    };
  }

  function dispatchAll(el) {
    if (!el) return;
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
  }

  function setSelectValue(sel, value) {
    if (!sel || value == null || value === '') return;
    var v = String(value).toLowerCase().trim();
    var opt = Array.prototype.find.call(sel.options, function (o) {
      return o.value.toLowerCase() === v;
    });
    if (!opt) {
      opt = Array.prototype.find.call(sel.options, function (o) {
        return o.textContent.toLowerCase().trim() === v;
      });
    }
    if (opt && opt.value) {
      sel.value = opt.value;
      dispatchAll(sel);
    }
  }

  function apply(data) {
    var typeSel = document.querySelector('#donation_donation_type');
    var donationDate = document.querySelector('#donation_donation_date');
    var depositDate = document.querySelector(
      '#donation_offline_donation_additional_detail_attributes_deposit_date'
    );
    var amount = document.querySelector('#amount');
    var orgComments = document.querySelector('#donation_org_comments');
    var checkNum = document.querySelector(
      '#donation_offline_donation_additional_detail_attributes_check_number'
    );

    if (data.donationType != null && data.donationType !== '') {
      setSelectValue(typeSel, data.donationType);
    }
    if (data.donationDate != null && data.donationDate !== '' && donationDate) {
      donationDate.value = String(data.donationDate).slice(0, 10);
      dispatchAll(donationDate);
    }
    if (data.depositDate != null && data.depositDate !== '' && depositDate) {
      depositDate.value = String(data.depositDate).slice(0, 10);
      dispatchAll(depositDate);
    }
    if (data.amount != null && data.amount !== '' && amount) {
      amount.value = String(data.amount);
      dispatchAll(amount);
    }
    if (data.orgComments != null && data.orgComments !== '' && orgComments) {
      orgComments.value = String(data.orgComments);
      dispatchAll(orgComments);
    }
    if (data.checkNumber != null && data.checkNumber !== '' && checkNum) {
      checkNum.value = String(data.checkNumber);
      dispatchAll(checkNum);
    }
  }

  function clearHashFromUrl() {
    var url = location.pathname + location.search;
    history.replaceState(null, '', url);
  }

  function tryDecodeAndApply() {
    var parsed = decodePayload(location.hash);
    if (!parsed) return;
    var data = normalizePayload(parsed);
    if (!data) return;
    var attempts = 0;
    function tryApply() {
      attempts++;
      var ready = document.querySelector('#amount');
      if (!ready && attempts < 40) {
        setTimeout(tryApply, 120);
        return;
      }
      if (!ready) {
        console.warn('[Donorbox prefill] Form not detected; leaving URL hash unchanged.');
        return;
      }
      apply(data);
      clearHashFromUrl();
      console.info('[Donorbox prefill] Applied offline payload.');
    }
    tryApply();
  }

  tryDecodeAndApply();
  window.addEventListener('hashchange', tryDecodeAndApply, false);
  document.addEventListener('turbo:load', tryDecodeAndApply, false);
  document.addEventListener('turbolinks:load', tryDecodeAndApply, false);
})();
