// ==UserScript==
// @name         Donorbox offline donation prefill
// @namespace    lrdc-offline-importer
// @version      1.0.0
// @description  Fills the Donorbox org-admin offline donation form from a URL hash payload (#dbOffline=...) generated by the launcher (Vercel-hosted or local). You must be logged in; complete captcha and submit manually if required.
// @match        https://donorbox.org/org_admin/supporters/*/donor_donations/new*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

/**
 * Form field map (from Donorbox org-admin offline donation form HTML):
 * - Payment type:     select#donation_donation_type  (donation[donation_type])
 * - Donation date:    input#donation_donation_date
 * - Deposit date:     input#donation_offline_donation_additional_detail_attributes_deposit_date
 * - Amount:           input#amount
 * - Org note:         textarea#donation_org_comments
 * - Check # (opt):    input#donation_offline_donation_additional_detail_attributes_check_number
 */

(function () {
  'use strict';

  var HASH_PREFIX = 'dbOffline=';

  function decodePayload(hash) {
    if (!hash || hash.charAt(0) !== '#') return null;
    var raw = hash.slice(1);
    if (raw.indexOf(HASH_PREFIX) !== 0) return null;
    var enc = raw.slice(HASH_PREFIX.length);
    if (!enc) return null;
    try {
      var b64 = enc.replace(/-/g, '+').replace(/_/g, '/');
      while (b64.length % 4) b64 += '=';
      var json = decodeURIComponent(escape(atob(b64)));
      return JSON.parse(json);
    } catch (e) {
      console.warn('[Donorbox prefill] Invalid payload', e);
      return null;
    }
  }

  function dispatchAll(el) {
    if (!el) return;
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
  }

  function setSelectValue(sel, value) {
    if (!sel || value == null || value === '') return;
    var v = String(value).toLowerCase().trim();
    var opt = Array.prototype.find.call(sel.options, function (o) {
      return o.value.toLowerCase() === v;
    });
    if (!opt) {
      opt = Array.prototype.find.call(sel.options, function (o) {
        return o.textContent.toLowerCase().trim() === v;
      });
    }
    if (opt && opt.value) {
      sel.value = opt.value;
      dispatchAll(sel);
    }
  }

  function apply(data) {
    var typeSel = document.querySelector('#donation_donation_type');
    var donationDate = document.querySelector('#donation_donation_date');
    var depositDate = document.querySelector(
      '#donation_offline_donation_additional_detail_attributes_deposit_date'
    );
    var amount = document.querySelector('#amount');
    var orgComments = document.querySelector('#donation_org_comments');
    var checkNum = document.querySelector(
      '#donation_offline_donation_additional_detail_attributes_check_number'
    );

    if (data.donationType != null && data.donationType !== '') {
      setSelectValue(typeSel, data.donationType);
    }
    if (data.donationDate != null && data.donationDate !== '' && donationDate) {
      donationDate.value = String(data.donationDate).slice(0, 10);
      dispatchAll(donationDate);
    }
    if (data.depositDate != null && data.depositDate !== '' && depositDate) {
      depositDate.value = String(data.depositDate).slice(0, 10);
      dispatchAll(depositDate);
    }
    if (data.amount != null && data.amount !== '' && amount) {
      amount.value = String(data.amount);
      dispatchAll(amount);
    }
    if (data.orgComments != null && orgComments) {
      orgComments.value = String(data.orgComments);
      dispatchAll(orgComments);
    }
    if (data.checkNumber != null && data.checkNumber !== '' && checkNum) {
      checkNum.value = String(data.checkNumber);
      dispatchAll(checkNum);
    }
  }

  function clearHashFromUrl() {
    var url = location.pathname + location.search;
    history.replaceState(null, '', url);
  }

  function run() {
    var data = decodePayload(location.hash);
    if (!data) return;
    var attempts = 0;
    function tryApply() {
      attempts++;
      var ready = document.querySelector('#amount');
      if (!ready && attempts < 25) {
        setTimeout(tryApply, 120);
        return;
      }
      if (!ready) {
        console.warn('[Donorbox prefill] Form not detected; leaving URL hash unchanged.');
        return;
      }
      apply(data);
      clearHashFromUrl();
      console.info('[Donorbox prefill] Applied offline payload.');
    }
    tryApply();
  }

  run();
})();
